---
title: "Technical variation report"
author: "SS"
date: "2023-12-05"
output: html_document
params: 
  x1: "NA"
  x2: "NA"
  x3: "NA" 
  x4: "NA"
  x5: "NA"
---
```{r setup, include=FALSE}
# assay_of_choice = "originalexp"
metadata_list <- lapply(params$x1, function(seurat_obj) {
  return(seurat_obj@meta.data)
})
# variable_genes_per_sample =
# 
#   # input
#   tibble(
#     seurat_obj_list = params$x1,
#     empty_droplets_obj_list = params$x2
#   ) |>
# 
#   # Reading input
#   mutate(variable_genes = map2(
#     seurat_obj_list, empty_droplets_obj_list,
#     ~ {
#       #browser()
#       seu = .x
#       if("HTO" %in% names(seu@assays)) seu[["HTO"]] = NULL
#       if("ADT" %in% names(seu@assays)) seu[["ADT"]] = NULL
# 
# 
#       # Filter
#       seu |>
#         left_join(.y) |>
#         dplyr::filter(!empty_droplet) |>
# 
#         # Scale
#         ScaleData(assay=assay_of_choice, return.only.var.genes=FALSE) |>
# 
#         # Variable features
#         FindVariableFeatures(assay=assay_of_choice, nfeatures = 500) |>
#         VariableFeatures(assay=assay_of_choice)
#     }
#   ))
# 

my_variable_genes = params$x3 |> 
  # pull(variable_genes) |> 
  unlist() 
#   unique()

```

## UMAP colored by Tissue 

```{r echo=FALSE, message=FALSE, warning=FALSE}
# data_umap =
# 
#   # input
#   dplyr::tibble(
#     seurat_obj_list = params$x1,
#     empty_droplets_obj_list = params$x2
#   ) |>
# 
#   # Reading input
#   dplyr::mutate(variable_genes = purrr::map2(
#     seurat_obj_list, empty_droplets_obj_list,
#     ~ {
#       #browser()
#       seu = .x
#       empty_droplets = .y
#       # Remove HTO and ADT assays if they are present
#       # if("HTO" %in% names(seu@assays)) seu[["HTO"]] = NULL
#       # if("ADT" %in% names(seu@assays)) seu[["ADT"]] = NULL
#       if("HTO" %in% names(seu@assays)) {
#         seu <- RemoveAssays(seu, assays = "HTO")
#         }
#       if("ADT" %in% names(seu@assays)) {
#         seu <- RemoveAssays(seu, assays = "ADT")
#       }
#       
#       # Filter empty droplets
#       # seu =
#       #   seu |>
#       #   left_join(.y) |>
#       #   dplyr::filter(!empty_droplet)
#       cells_to_keep <- empty_droplets %>% 
#         dplyr::filter(!empty_droplet) %>% 
#         pull(.cell)
#       
#       seu <- subset(seu, cells = cells_to_keep)
#       
#       variable_genes_present <- intersect(my_variable_genes, rownames(seu))
#       sampled_genes <- sample(variable_genes_present, min(length(variable_genes_present), 1000))
#       seu <- seu[sampled_genes, ]
#       
#       return(seu)
#       # seu =
#       #   seu[my_variable_genes,] |>
#       #   slice_sample( n=min(ncol(seu), 1000), replace = FALSE )
#     }
#   )) 

# data_umap = map(params$x1, function(seu) {
#   #browser()
#   seu <- ScaleData(seu, assay = assay_of_choice, features = rownames(seu), return.only.var.genes = FALSE)
#   VariableFeatures(seu) <- my_variable_genes
#   seu<- RunPCA(seu, dims = 1:30, assay=assay_of_choice) |>
#     RunUMAP(dims = 1:30, spread = 0.5,min.dist  = 0.01, n.neighbors = 10L) 
#     # as_tibble() |>
#     # left_join(input_metadata)
#   
#   # Extract UMAP coordinates and any other relevant data for plotting
#   umap_data <- FetchData(seu, vars = c("umap_1", "umap_2", "Tissue"))
#   
#   return(umap_data)
# }) %>% bind_rows()

  # #unnest(variable_genes) %>%
  # ScaleData(assay=assay_of_choice, return.only.var.genes=FALSE) %>%
  # # Variable genes
  # {
  #   .x = (.)
  #   VariableFeatures(.x) = my_variable_genes
  #   .x
  # } |>
  # 
  # # UMAP
  # RunPCA(dims = 1:30, assay=assay_of_choice) |>
  # RunUMAP(dims = 1:30, spread = 0.5,min.dist  = 0.01, n.neighbors = 10L) |>
  # as_tibble() |>
  # 
  # left_join(input_metadata) 
data_umap<- params$x4 %>% bind_rows()
# Plot
plot_tissue_color =
    data_umap |>
    dplyr::mutate(batch = 1) |>
    ggplot(aes(umap_1, umap_2, color = data_umap[[params$x5]])) +  # Ensure 'Tissue' is a column in 'data_umap'
    geom_point(size = 0.2) +
    facet_wrap(~data_umap[[params$x5]]) +
    theme_minimal() +
    labs(title = "UMAP colored by Tissue", color = "data_umap[[params$x5]]")

# plot_severity_color =
#   data_umap |>
#   mutate(batch = 1) |>
#   # UMAP
#   ggplot(aes(umap_1, umap_2, color = severity)) +
#   geom_point(size=0.2) +
#   facet_wrap(~batch) +
#   guides(color="none") +
#   theme_multipanel

# plot_batch_color =
#   data_umap |>
#   
#   mutate(batch = 1) |>
# 
#   # UMAP
#   ggplot(aes(UMAP_1, UMAP_2, color = batch)) +
#   geom_point(size=0.2) +
#   theme_multipanel
print(plot_tissue_color)
```


